version: "3"

services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/core/nginx.conf:/etc/nginx/nginx.conf
      - ../amigo/:/var/www/amigo/
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/ssl/:/etc/ssl/
      - ./nginx/snippets/:/etc/nginx/snippets/
    links:
      - php

  mysql:
    image: mysql:8.0.22
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=amigo
      - MYSQL_USER=amigo
      - MYSQL_PASSWORD=123456
    volumes:
      - ./mysql/data:/var/lib/mysql

  php:
    build: ./php
    restart: always
    links:
      - mysql
    volumes:
      - ../amigo/:/var/www/amigo/
